add badges to readme and setup readthedoc

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,12 +32,12 @@ jobs:
         run: yarn install
       - name: TypeScript Tests
         run: yarn test:coverage --ci
-      - name: "Codacy: Report coverage"
-        uses: codacy/codacy-coverage-reporter-action@master
-        with:
-          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
-          coverage-reports: coverage/lcov.info
-        if: success() || failure()
+#      - name: "Codacy: Report coverage"
+#        uses: codacy/codacy-coverage-reporter-action@master
+#        with:
+#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
+#          coverage-reports: coverage/lcov.info
+#        if: success() || failure()
       - name: TypeScript Formatting
         run: yarn prettier:check
         if: success() || failure()
